======="
echo ""
echo "注意事项:"
echo "  1. 确保 DTB 中已配置 realtek,led-mode 属性"
echo "  2. 如 DTB 中仍是 realtek,led-data，请运行 fix_dtb_led_mode.sh"
echo "  3. 如驱动异常，恢复原驱动:"
echo "     sudo cp $DRIVER_PATH.bak.* $DRIVER_PATH"
echo "     sudo modprobe -r r8169 && sudo modprobe r8169"
echo "     sudo systemctl enable --now $LED_SERVICE"
